### ISSUE TITLE
No module named 'clev'

### ISSUE THREAD

**Issue by ReallyNewToPython** [infoscout/weighted-levenshtein#1]
Using Python 3.5, have installed package. Believe I have Cython compiler.
![error](https://cloud.githubusercontent.com/assets/21954785/18207917/28bf3e42-7125-11e6-98ed-766b3a68db0f.jpg)

**Comment by RevolutionTech** [comment]
Sorry @ReallyNewToPython! `weighted-levenshtein` does not currently support Python 3. Currently we only have support for Python 2.7.
