### ISSUE TITLE
The substitution score is limited to 2

### ISSUE THREAD

**Issue by albodrug** [infoscout/weighted-levenshtein#10]
Hi there, 

```python
#!/usr/bin/python3`

import numpy as np
from weighted_levenshtein import lev, osa, dam_lev
substitute_costs = np.ones((128, 128), dtype=np.float64)
substitute_costs[ord('H'), ord('B')] = 2
substitute_costs[ord('B'), ord('H')] = 2

print(lev('HANANA', 'BANANA', `substitute_costs=substitute_costs))
```
Output: 2

```python
#!/usr/bin/python3

import numpy as np
from weighted_levenshtein import lev, osa, dam_lev
substitute_costs = np.ones((128, 128), dtype=np.float64)
substitute_costs[ord('H'), ord('B')] = 9
substitute_costs[ord('B'), ord('H')] = 9

print(lev('HANANA', 'BANANA', substitute_costs=substitute_costs))
```

Output:2

Is there a reason for the substitution score to be limited to 2? Also, I did not check the other costs, so it might be the same.

Best, 
Alex

**Comment by dsu1995** [comment]
Since you did not change the insertion and deletion costs, they remain at the default, which is 1.
`HANANA` can be transformed to `BANANA` with 1 delete of `H` and 1 insert of `B`, giving a total cost of 2. Thus, increasing the substitution costs to 9 would have no effect in this case.
