### ISSUE TITLE
Cython Requirement

### ISSUE THREAD

**Issue by khanguslee** [infoscout/weighted-levenshtein#11]
Would be good to include on the README.md that you need Cython installed as a prequisite before installing the library using pip.

**Comment by RevolutionTech** [comment]
Thanks for bringing this issue to my attention. `Cython` should be automatically installed when installing the `weighted-levenshtein` library with pip. However, there was indeed a bug in `setup.py` that was causing that to not work correctly.

I just created https://github.com/infoscout/weighted-levenshtein/pull/12 that addresses this. Could you please verify that this fix works for you in a clean virtualenv?

**Comment by khanguslee** [comment]
Can confirm the fix works!
