### ISSUE TITLE
error: unknown file type '.pyx' 

### ISSUE THREAD

**Issue by akbar20gh** [infoscout/weighted-levenshtein#14]
Hi
I install weighted-levenshtein but error this:
Python 2.7.10 :: Anaconda 2.3.0 (64-bit)

pip install weighted-levenshtein
Collecting weighted-levenshtein
  Using cached https://files.pythonhosted.org/packages/7d/f2/17dfcf4d36abf33c8b50a664bf64685f6ba37cb477f96433a04835c7c84b/weighted_levenshtein-0.2.1.tar.gz
Installing collected packages: weighted-levenshtein
  Running setup.py install for weighted-levenshtein ... error
    Complete output from command /home/yamahdi/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-VXoAI9/weighted-levenshtein/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-IZTwW6/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/weighted_levenshtein
    copying weighted_levenshtein/__init__.py -> build/lib.linux-x86_64-2.7/weighted_levenshtein
    copying weighted_levenshtein/clev.pxd -> build/lib.linux-x86_64-2.7/weighted_levenshtein
    copying weighted_levenshtein/clev.pyx -> build/lib.linux-x86_64-2.7/weighted_levenshtein
    running build_ext
    building 'weighted_levenshtein.clev' extension
    error: unknown file type '.pyx' (from 'weighted_levenshtein/clev.pyx')
    
    ----------------------------------------
Command "/home/yamahdi/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-VXoAI9/weighted-levenshtein/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-IZTwW6/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-VXoAI9/weighted-levenshtein/

**Comment by RevolutionTech** [comment]
What version of `setuptools` do you have?

**Comment by akbar20gh** [comment]
Hi, thank
it because of my cython version. I update it.
thanks
