### ISSUE TITLE
Weights for similar looking characters

### ISSUE THREAD

**Issue by danielsnider** [infoscout/weighted-levenshtein#17]
I think we have similar uses cases: for a string metric that is made for OCR mistake matching. This would be really, really amazing help for our health science research at the Hospital for Sick Children, in Toronto. 

Can you release a weight set that is optimized for matching strings for OCR detection? I'm looking for a list of costs that you use to improve your matching metric for similar looking characters.

This use case permeates your documentation, for example:
> However, sometimes not all edits are created equal. For instance, if you are doing OCR correction, maybe substituting ‘0’ for ‘O’ should have a smaller cost than substituting ‘X’ for ‘O’. 

Can you please share your weights so that I don't have to reinvent the wheel?

Thank you! You're helping science!

**Comment by RevolutionTech** [comment]
Unfortunately, I'm not sure that our weights would be helpful to you- they may just lead you in the wrong direction. We generated our weights based on the datasets we're operating on, which is primarily OCR text from receipt images.

As an oversimplified example, numbers will appear in receipts far more than in a fiction novel, so our weights will reflect this.

I'm sorry that we can't be of more help.
