### ISSUE TITLE
Are common costs included in the package?

### ISSUE THREAD

**Issue by ReallyNewToPython** [infoscout/weighted-levenshtein#2]
Hi. Have managed to get the package to work by using Python 2.7.

I note from your article that "To quantify [common typing mistakes], we collected statistics from our proprietary data to determine the frequencies of each type of error, from both humans and OCR. These frequencies were then transformed into costs" because "we could not find any existing library out there that can calculate weighted Levenshtein and weighted Damerau-Levenshtein distance. Thus, we built a library to do this ourselves." Is this cost information available from the package? Or elsewhere?

Regards.

**Comment by dsu1995** [comment]
Unfortunately, the costs were calculated from our proprietary data, so we will not be releasing this information. The costs will be different for different use cases, so our data may not be applicable to you. You can try searching online to see if you can find this data, or try to "estimate" the costs yourself.

**Comment by jtlz2** [comment]
@ReallyNewToPython Did you have any success in finding some typical weights for OCR and/or QWERTY?

@dsu1995 Thank you for such an amazingly useful piece of software!

**Comment by ReallyNewToPython** [comment]
I'm afraid not.
________________________________

**Comment by KeironO** [comment]
I've hacked together the following for QWERTY costs:

```python
import numpy as np
import math

distances = {}

keyboard_layout = '0123456789¿qwertyuiop¿asdfghjkl¿zxcvbnm'

class Location:
    def __init__(self, x, y):
        self.x = x
        self.y = y
        

for row_id, row in enumerate(keyboard_layout.split("¿")):
    for key_id, key in enumerate(row):
        distances[key] = Location(key_id, row_id)
        
def eucdistance(v1, v2):
    v1 = distances[v1]
    v2 = distances[v2]
    
    x = math.pow(v1.x - v2.x, 2)
    y = math.pow(v1.y - v2.y, 2 )
    
    return math.sqrt(x+y)

def compare(s1, s2):
    if len(s1) != len(s2):
        return -1
    
    distance = 0
    
    for i, _ in enumerate(s1):
        if s1[i] != s2[i]:
            res = eucdistance(s1[i], s2[i])
            if res == -1:
                return res
        
            distance += res
        
    return distance

substitute_costs = np.ones((128, 128), dtype=np.float64)

for row in keyboard_layout.split("¿"):
    for letter in row:
        for x in keyboard_layout:
            if x != "¿":
                substitute_costs[ord(letter), ord(x)] = compare(letter, x)
```

**Comment by GoulartNogueira** [comment]
Thanks @KeironO 
Nice approach for typing errors!
(Minor fix: Keyboard numbers goes from 1->0, instead of 0->9)

**Comment by GoulartNogueira** [comment]
### Idea for Automatic OCR table generation:

We could follow a similar approach to compare pixel space:
1. Get each character
2. Turn into image
3. Compare pixel distance for each pair of characters

Then improve it even further, by tuning:
- Variations (repeat for many varieties, to have a robust metric)
  - Common fonts
  - Bold, italic, ...
- Image similarity metric
  - Pick a good metric, such as [SSIM](https://en.wikipedia.org/wiki/Structural_similarity_index_measure) and [many more](https://up42.com/blog/image-similarity-measures)
  - Have a small penalty for some realigning transformations
  - For example: An `italic L` looks like a `slash`: (_l_ /).
  - A direct image comparison will have a low match. but if you allow rotation and translation, they are very similar.
- Character Pairs
  - OCR usually splits or merges characters.
  - For example `M` <--> `IN` | `h`<--> `ln` | `VV` <-> `W`
  - There could be a complete table comparing character against pairs.
