### ISSUE TITLE
ImportError: No module named 'clev'

### ISSUE THREAD

**Issue by PieterFivez** [infoscout/weighted-levenshtein#3]
Hi,

I have installed the package, but when I try to import it in Python 3, the __init__.py file throws an ImportError: No module named 'clev', while the file clev.pyx is there in the package. The same issue arises on another computer. Any idea what is going on here?

Thank you.

**Comment by RevolutionTech** [comment]
Sorry @PieterFivez! `weighted-levenshtein` does not currently support Python 3. Currently we only have support for Python 2.7.
