### ISSUE TITLE
Issue of "No module named 'clev'" when imported

### ISSUE THREAD

**Issue by weilong-l** [infoscout/weighted-levenshtein#5]
When I tried to import your package, I got this ImportError

**Comment by pachewise** [comment]
1. Did you use `pip` to install this library?
2. What version of Python are you using? (This library is untested on Python 3).

**Comment by RevolutionTech** [comment]
The library was built for Python 2 and does not support Python 3, which is mentioned in the README. I'll close this issue out, but feel free to reply if you are still running into this issue on Python 2.7.
