### ISSUE TITLE
Latest version not available through pip

### ISSUE THREAD

**Issue by diegodlh** [infoscout/weighted-levenshtein#8]
The latest version available through the repository implemented a change in __init__.py file which leads to successfully loading of the .clev library. However, this change is not reflected in the PyPi repository (not even in the TestPyPi, which has version 0.9). I'm not sure whether this the place to report this issue, but it might be worth fixing it as it may be hard for a user downloading the module through pip (which is the way suggested in the readme) to figure out what is going on.

**Comment by RevolutionTech** [comment]
Apologies for the late response! Thanks for creating an issue for this @diegodlh. I've uploaded v0.2 to PyPi.
